name: Minikube CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
        with:
          minikube-version: 'v1.32.0'
          kubernetes-version: 'v1.28.3'
          driver: docker

      - name: Check Minikube status
        run: |
          minikube status
          kubectl get nodes

      - name: Deploy to Minikube
        run: |
          kubectl create deployment nginx --image=nginx
          kubectl expose deployment nginx --port=80 --type=NodePort
          kubectl get svc

      - name: Test service
        run: |
          URL=$(minikube service nginx --url)
          echo "Testing $URL"
          curl -s $URL

