name: Minikube CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube (as non-root user)
        run: |
          # Create a new user for non-root Minikube
          sudo useradd -m minikubeuser
          
          # Add user to the Docker group to allow access to Docker
          sudo usermod -aG docker minikubeuser
          
          # Switch to non-root user and start Minikube
          sudo su - minikubeuser -c "newgrp docker; minikube start --driver=docker"
          sudo su - minikubeuser -c "minikube status"

      - name: Deploy NGINX
        run: |
          sudo su - minikubeuser -c "newgrp docker; kubectl create deployment nginx --image=nginx"
          sudo su - minikubeuser -c "newgrp docker; kubectl expose deployment nginx --port=80 --type=NodePort"
          sudo su - minikubeuser -c "newgrp docker; kubectl get svc"

      - name: Test Service
        run: |
          URL=$(sudo su - minikubeuser -c "newgrp docker; minikube service nginx --url")
          echo "Testing $URL"
          curl -s $URL
